services:
  frontend:
    build: .
    ports:
      - "${APP_PORT:-8080}:80"
    environment:
      CI_ENVIRONMENT: "${CI_ENVIRONMENT:-development}"
      API_URL: "${API_URL:-http://127.0.0.1:8000/api/v1/}"
      app_baseURL: "${APP_URL:-https://projects.tail5e7fd8ts.net/}"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - writable_data:/var/www/html/writable

volumes:
  writable_data:

